[package]
name = "device-driver"
version = "0.6.0"
authors = ["Dion Dokter <diondokter@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/diondokter/device-driver"
repository = "https://github.com/diondokter/device-driver"
keywords = ["no_std", "device", "driver", "toolkit"]
categories = ["embedded", "hardware-support", "no-std"]
description = "A toolkit to write better device drivers, faster"
readme.workspace = true

[dependencies]
device-driver-macros = { version = "0.6.0", path = "../macros" }

bitvec = { version = "1.0.1", default-features = false }
funty = { version = "2.0.0", default-features = false }
num_enum = { version = "0.7.1", default-features = false }
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"

[features]
json = ["device-driver-macros/json"]
yaml = ["device-driver-macros/yaml"]

[[example]]
name = "test-json-driver"
required-features = ["json"]
[[example]]
name = "test-yaml-driver"
required-features = ["yaml"]
[[example]]
name = "test-macro-driver"
