[package]
name = "device-driver"
version = "0.7.0"
authors = ["Dion Dokter <diondokter@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/diondokter/device-driver"
repository = "https://github.com/diondokter/device-driver"
keywords = ["no_std", "device", "driver", "toolkit"]
categories = ["embedded", "hardware-support", "no-std"]
description = "A toolkit to write better device drivers, faster"
readme.workspace = true

[dependencies]
device-driver-macros = { version = "0.7.0", path = "../macros", optional = true }

bitvec = { version = "1.0.1", default-features = false }
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"

[features]
default = ["macros", "json", "yaml", "toml"]
macros = ["dep:device-driver-macros"]
json = ["macros", "device-driver-macros/json"]
yaml = ["macros", "device-driver-macros/yaml"]
toml = ["macros", "device-driver-macros/toml"]
