[package]
name = "device-driver"
version = "0.4.1"
authors = ["Dion Dokter <diondokter@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/diondokter/device-driver"
repository = "https://github.com/diondokter/device-driver"
readme = "README.md"
keywords = ["no_std", "device", "driver", "toolkit"]
categories = ["embedded", "hardware-support", "no-std"]
description = "A toolkit to write better device drivers, faster"

[dependencies]
device-driver-core = { path = "../core" }
indexmap = { version = "2.1.0", features = ["serde"] }
serde = { version = "1.0.193", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.108"
