[package]
name = "device-driver-cli"
version = "1.0.1"
authors = ["Dion Dokter <diondokter@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/diondokter/device-driver"
repository = "https://github.com/diondokter/device-driver"
keywords = ["device", "driver", "toolkit"]
categories = ["embedded", "hardware-support", "development-tools"]
description = "The command line tool for the device-driver toolkit"
readme = "README.md"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
device-driver-generation = { version = "=1.0.1", path = "../generation" }
prettyplease = { version = "0.2.22", features = ["verbatim"] }
syn = { version = "2.0" }
