[package]
name = "device-driver-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
device-driver-generation = { path = "../generation" }
syn = { version = "2.0", features = ["extra-traits"] }
serde_json = "1.0"
serde_yaml = "0.9"
proc-macro2 = "1.0"
quote = "1.0"
