[package]
name = "device-driver-generation"
version = "0.5.0"
authors = ["Dion Dokter <diondokter@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/diondokter/device-driver"
repository = "https://github.com/diondokter/device-driver"
readme = "../README.md"
keywords = ["no_std", "device", "driver", "toolkit"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Code generation for the `device-driver` crate"

[dependencies]
convert_case = "0.6.0"
indexmap = { version = "2.1.0", features = ["serde"] }
prettyplease = "0.2.15"
proc-macro2 = "1.0.70"
quote = "1.0.33"
serde = { version = "1.0.193", features = ["derive"] }
syn = "2.0.39"

[dev-dependencies]
serde_json = "1.0.108"
serde_yaml = "0.9.27"
pretty_assertions = "1.4.0"
